// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type LandingDocumentDataSlicesSlice =
  | ClientLogosSlice
  | StickyHeaderSlice
  | WorkGridSlice
  | ContactSlice
  | HeroVideoSlice
  | CookieFooterSlice
  | PhilosophySlice
  | ProfileWorkGridSlice
  | AddressSlice;

/**
 * Content for landing documents
 */
interface LandingDocumentData {
  /**
   * Title field in *landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Keywords field in *landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.keywords
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keywords: prismic.KeyTextField;

  /**
   * Slice Zone field in *landing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandingDocumentDataSlicesSlice>;
}

/**
 * landing document from Prismic
 *
 * - **API ID**: `landing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LandingDocumentData>,
    "landing",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | TextSlice
  | StickyHeaderSlice
  | WorkGridSlice
  | ImageSliceSlice
  | RichTextSlice
  | ContactSlice
  | HeroTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Descript field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Keywords field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.keywords
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keywords: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type SettingsDocumentDataSlicesSlice = MediaArraySlice | LinksSlice;

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
  /**
   * Title field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * logo field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * placeholderImage field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.placeholderimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  placeholderimage: prismic.ImageField<never>;

  /**
   * Slice Zone field in *settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>;
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type WorkDocumentDataSlicesSlice = WorkCarouselSlice | TextSlice;

/**
 * Content for Work documents
 */
interface WorkDocumentData {
  /**
   * Title field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Keywords field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.keywords
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keywords: prismic.KeyTextField;

  /**
   * NextWork field in *Work*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: work.nextwork
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nextwork: prismic.ContentRelationshipField;

  /**
   * Description field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Credits field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.credits
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  credits: prismic.KeyTextField;

  /**
   * Slice Zone field in *Work*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: work.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<WorkDocumentDataSlicesSlice>;
}

/**
 * Work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<WorkDocumentData>, "work", Lang>;

export type AllDocumentTypes =
  | LandingDocument
  | PageDocument
  | SettingsDocument
  | WorkDocument;

/**
 * Primary content in *Address → Default → Primary*
 */
export interface AddressSliceDefaultPrimary {
  /**
   * Title field in *Address → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: address.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Address → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: address.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Address → Items*
 */
export interface AddressSliceDefaultItem {
  /**
   * AddressLine field in *Address → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: address.items[].addressline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  addressline: prismic.RichTextField;

  /**
   * PhoneLine field in *Address → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: address.items[].phoneline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phoneline: prismic.RichTextField;

  /**
   * EmailLine field in *Address → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: address.items[].emailline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  emailline: prismic.RichTextField;
}

/**
 * Default variation for Address Slice
 *
 * - **API ID**: `default`
 * - **Description**: Address
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AddressSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AddressSliceDefaultPrimary>,
  Simplify<AddressSliceDefaultItem>
>;

/**
 * Slice variation for *Address*
 */
type AddressSliceVariation = AddressSliceDefault;

/**
 * Address Shared Slice
 *
 * - **API ID**: `address`
 * - **Description**: Address
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AddressSlice = prismic.SharedSlice<
  "address",
  AddressSliceVariation
>;

/**
 * Primary content in *ClientLogos → Default → Primary*
 */
export interface ClientLogosSliceDefaultPrimary {
  /**
   * Title field in *ClientLogos → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: client_logos.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Order field in *ClientLogos → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: client_logos.default.primary.order
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;

  /**
   * Negative Order field in *ClientLogos → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: client_logos.default.primary.negative_order
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  negative_order: prismic.NumberField;

  /**
   * SubOrder field in *ClientLogos → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: client_logos.default.primary.suborder
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  suborder: prismic.NumberField;
}

/**
 * Primary content in *ClientLogos → Items*
 */
export interface ClientLogosSliceDefaultItem {
  /**
   * Logo field in *ClientLogos → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: client_logos.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * link field in *ClientLogos → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: client_logos.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for ClientLogos Slice
 *
 * - **API ID**: `default`
 * - **Description**: ClientLogos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientLogosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ClientLogosSliceDefaultPrimary>,
  Simplify<ClientLogosSliceDefaultItem>
>;

/**
 * Slice variation for *ClientLogos*
 */
type ClientLogosSliceVariation = ClientLogosSliceDefault;

/**
 * ClientLogos Shared Slice
 *
 * - **API ID**: `client_logos`
 * - **Description**: ClientLogos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientLogosSlice = prismic.SharedSlice<
  "client_logos",
  ClientLogosSliceVariation
>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Order field in *Contact → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.order
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;

  /**
   * Negative Order field in *Contact → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.negative_order
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  negative_order: prismic.NumberField;
}

/**
 * Primary content in *Contact → Items*
 */
export interface ContactSliceDefaultItem {
  /**
   * Title field in *Contact → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Address field in *Contact → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Address...
   * - **API ID Path**: contact.items[].address
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;

  /**
   * link1 field in *Contact → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.items[].link1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link1: prismic.LinkField;

  /**
   * text1 field in *Contact → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.items[].text1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text1: prismic.KeyTextField;

  /**
   * link2 field in *Contact → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.items[].link2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link2: prismic.LinkField;

  /**
   * text2 field in *Contact → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.items[].text2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text2: prismic.KeyTextField;

  /**
   * link3 field in *Contact → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.items[].link3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link3: prismic.LinkField;

  /**
   * text3 field in *Contact → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.items[].text3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text3: prismic.KeyTextField;

  /**
   * link4 field in *Contact → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.items[].link4
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link4: prismic.LinkField;

  /**
   * text4 field in *Contact → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.items[].text4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text4: prismic.KeyTextField;

  /**
   * link5 field in *Contact → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.items[].link5
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link5: prismic.LinkField;

  /**
   * text5 field in *Contact → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.items[].text5
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text5: prismic.KeyTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  Simplify<ContactSliceDefaultItem>
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *CookieFooter → Default → Primary*
 */
export interface CookieFooterSliceDefaultPrimary {
  /**
   * Content field in *CookieFooter → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie_footer.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * ImprintLink field in *CookieFooter → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie_footer.default.primary.imprintlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  imprintlink: prismic.ContentRelationshipField;

  /**
   * Order field in *CookieFooter → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie_footer.default.primary.order
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;

  /**
   * Negative Order field in *CookieFooter → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie_footer.default.primary.negative_order
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  negative_order: prismic.NumberField;
}

/**
 * Default variation for CookieFooter Slice
 *
 * - **API ID**: `default`
 * - **Description**: CookieFooter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CookieFooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CookieFooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CookieFooter*
 */
type CookieFooterSliceVariation = CookieFooterSliceDefault;

/**
 * CookieFooter Shared Slice
 *
 * - **API ID**: `cookie_footer`
 * - **Description**: CookieFooter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CookieFooterSlice = prismic.SharedSlice<
  "cookie_footer",
  CookieFooterSliceVariation
>;

/**
 * Primary content in *CreditFooter → Default → Primary*
 */
export interface CreditFooterSliceDefaultPrimary {
  /**
   * Line One field in *CreditFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: credit_footer.default.primary.line_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  line_one: prismic.KeyTextField;

  /**
   * Line Two field in *CreditFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: credit_footer.default.primary.line_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  line_two: prismic.KeyTextField;

  /**
   * Order field in *CreditFooter → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: credit_footer.default.primary.order
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;

  /**
   * Negative Order field in *CreditFooter → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: credit_footer.default.primary.negative_order
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  negative_order: prismic.NumberField;

  /**
   * Logo field in *CreditFooter → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: credit_footer.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for CreditFooter Slice
 *
 * - **API ID**: `default`
 * - **Description**: CreditFooter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CreditFooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CreditFooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CreditFooter*
 */
type CreditFooterSliceVariation = CreditFooterSliceDefault;

/**
 * CreditFooter Shared Slice
 *
 * - **API ID**: `credit_footer`
 * - **Description**: CreditFooter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CreditFooterSlice = prismic.SharedSlice<
  "credit_footer",
  CreditFooterSliceVariation
>;

/**
 * Primary content in *HeroText → Items*
 */
export interface HeroTextSliceDefaultItem {
  /**
   * Hero Text field in *HeroText → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_text.items[].hero_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_text: prismic.KeyTextField;
}

/**
 * Default variation for HeroText Slice
 *
 * - **API ID**: `default`
 * - **Description**: HeroText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<HeroTextSliceDefaultItem>
>;

/**
 * Slice variation for *HeroText*
 */
type HeroTextSliceVariation = HeroTextSliceDefault;

/**
 * HeroText Shared Slice
 *
 * - **API ID**: `hero_text`
 * - **Description**: HeroText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroTextSlice = prismic.SharedSlice<
  "hero_text",
  HeroTextSliceVariation
>;

/**
 * Primary content in *HeroVideo → Default → Primary*
 */
export interface HeroVideoSliceDefaultPrimary {
  /**
   * VideoLink field in *HeroVideo → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_video.default.primary.videolink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  videolink: prismic.LinkToMediaField;

  /**
   * Image field in *HeroVideo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_video.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for HeroVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: HeroVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroVideo*
 */
type HeroVideoSliceVariation = HeroVideoSliceDefault;

/**
 * HeroVideo Shared Slice
 *
 * - **API ID**: `hero_video`
 * - **Description**: HeroVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroVideoSlice = prismic.SharedSlice<
  "hero_video",
  HeroVideoSliceVariation
>;

/**
 * Primary content in *ImageSlice → Default → Primary*
 */
export interface ImageSliceSliceDefaultPrimary {
  /**
   * Title field in *ImageSlice → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: image_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Image field in *ImageSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slice.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: ImageSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageSlice*
 */
type ImageSliceSliceVariation = ImageSliceSliceDefault;

/**
 * ImageSlice Shared Slice
 *
 * - **API ID**: `image_slice`
 * - **Description**: ImageSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceSlice = prismic.SharedSlice<
  "image_slice",
  ImageSliceSliceVariation
>;

/**
 * Primary content in *Links → Items*
 */
export interface LinksSliceDefaultItem {
  /**
   * link1 field in *Links → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: links.items[].link1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link1: prismic.LinkField;

  /**
   * text1 field in *Links → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: links.items[].text1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text1: prismic.KeyTextField;

  /**
   * link2 field in *Links → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: links.items[].link2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link2: prismic.LinkField;

  /**
   * text2 field in *Links → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: links.items[].text2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text2: prismic.KeyTextField;

  /**
   * link3 field in *Links → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: links.items[].link3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link3: prismic.LinkField;

  /**
   * text3 field in *Links → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: links.items[].text3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text3: prismic.KeyTextField;

  /**
   * link4 field in *Links → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: links.items[].link4
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link4: prismic.LinkField;

  /**
   * text4 field in *Links → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: links.items[].text4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text4: prismic.KeyTextField;

  /**
   * link5 field in *Links → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: links.items[].link5
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link5: prismic.LinkField;

  /**
   * text5 field in *Links → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: links.items[].text5
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text5: prismic.KeyTextField;
}

/**
 * Default variation for Links Slice
 *
 * - **API ID**: `default`
 * - **Description**: Links
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<LinksSliceDefaultItem>
>;

/**
 * Slice variation for *Links*
 */
type LinksSliceVariation = LinksSliceDefault;

/**
 * Links Shared Slice
 *
 * - **API ID**: `links`
 * - **Description**: Links
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinksSlice = prismic.SharedSlice<"links", LinksSliceVariation>;

/**
 * Primary content in *MediaArray → Default → Primary*
 */
export interface MediaArraySliceDefaultPrimary {
  /**
   * Title field in *MediaArray → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: media_array.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *MediaArray → Items*
 */
export interface MediaArraySliceDefaultItem {
  /**
   * media field in *MediaArray → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: media_array.items[].media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  media: prismic.LinkToMediaField;
}

/**
 * Default variation for MediaArray Slice
 *
 * - **API ID**: `default`
 * - **Description**: MediaArray
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaArraySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MediaArraySliceDefaultPrimary>,
  Simplify<MediaArraySliceDefaultItem>
>;

/**
 * Slice variation for *MediaArray*
 */
type MediaArraySliceVariation = MediaArraySliceDefault;

/**
 * MediaArray Shared Slice
 *
 * - **API ID**: `media_array`
 * - **Description**: MediaArray
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaArraySlice = prismic.SharedSlice<
  "media_array",
  MediaArraySliceVariation
>;

/**
 * Primary content in *Philosophy → Default → Primary*
 */
export interface PhilosophySliceDefaultPrimary {
  /**
   * Title field in *Philosophy → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: philosophy.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * SubOrder field in *Philosophy → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: philosophy.default.primary.suborder
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  suborder: prismic.NumberField;

  /**
   * Order field in *Philosophy → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: philosophy.default.primary.order
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;
}

/**
 * Primary content in *Philosophy → Items*
 */
export interface PhilosophySliceDefaultItem {
  /**
   * Type field in *Philosophy → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: philosophy.items[].type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"Description with image" | "List">;

  /**
   * Category field in *Philosophy → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: philosophy.items[].category
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  category: prismic.TitleField;

  /**
   * Big Text field in *Philosophy → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: philosophy.items[].bigtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bigtext: prismic.RichTextField;

  /**
   * Image field in *Philosophy → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: philosophy.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * List Heading field in *Philosophy → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: philosophy.items[].list_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_heading: prismic.TitleField;

  /**
   * List field in *Philosophy → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: philosophy.items[].list
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list: prismic.RichTextField;

  /**
   * text field in *Philosophy → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: philosophy.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Philosophy Slice
 *
 * - **API ID**: `default`
 * - **Description**: Philosophy
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhilosophySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PhilosophySliceDefaultPrimary>,
  Simplify<PhilosophySliceDefaultItem>
>;

/**
 * Slice variation for *Philosophy*
 */
type PhilosophySliceVariation = PhilosophySliceDefault;

/**
 * Philosophy Shared Slice
 *
 * - **API ID**: `philosophy`
 * - **Description**: Philosophy
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhilosophySlice = prismic.SharedSlice<
  "philosophy",
  PhilosophySliceVariation
>;

/**
 * Primary content in *ProfileWorkGrid → Default → Primary*
 */
export interface ProfileWorkGridSliceDefaultPrimary {
  /**
   * Title field in *ProfileWorkGrid → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: profile_work_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *ProfileWorkGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: profile_work_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *ProfileWorkGrid → Items*
 */
export interface ProfileWorkGridSliceDefaultItem {
  /**
   * projectLink field in *ProfileWorkGrid → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: profile_work_grid.items[].projectlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  projectlink: prismic.LinkField;

  /**
   * media field in *ProfileWorkGrid → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: profile_work_grid.items[].media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  media: prismic.LinkToMediaField;

  /**
   * title field in *ProfileWorkGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: profile_work_grid.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for ProfileWorkGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: ProfileWorkGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProfileWorkGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProfileWorkGridSliceDefaultPrimary>,
  Simplify<ProfileWorkGridSliceDefaultItem>
>;

/**
 * Slice variation for *ProfileWorkGrid*
 */
type ProfileWorkGridSliceVariation = ProfileWorkGridSliceDefault;

/**
 * ProfileWorkGrid Shared Slice
 *
 * - **API ID**: `profile_work_grid`
 * - **Description**: ProfileWorkGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProfileWorkGridSlice = prismic.SharedSlice<
  "profile_work_grid",
  ProfileWorkGridSliceVariation
>;

/**
 * Primary content in *Article → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Title field in *Article → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: rich_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *Article → Items*
 */
export interface RichTextSliceDefaultItem {
  /**
   * Content field in *Article → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Article Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  Simplify<RichTextSliceDefaultItem>
>;

/**
 * Slice variation for *Article*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * Article Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *StickyHeader → Default → Primary*
 */
export interface StickyHeaderSliceDefaultPrimary {
  /**
   * Title field in *StickyHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sticky_header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Order field in *StickyHeader → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: sticky_header.default.primary.order
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;

  /**
   * Negative Order field in *StickyHeader → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: sticky_header.default.primary.negative_order
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  negative_order: prismic.NumberField;
}

/**
 * Default variation for StickyHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: StickyHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StickyHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StickyHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StickyHeader*
 */
type StickyHeaderSliceVariation = StickyHeaderSliceDefault;

/**
 * StickyHeader Shared Slice
 *
 * - **API ID**: `sticky_header`
 * - **Description**: StickyHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StickyHeaderSlice = prismic.SharedSlice<
  "sticky_header",
  StickyHeaderSliceVariation
>;

/**
 * Primary content in *CarouselDescription → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Title field in *CarouselDescription → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *CarouselDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: text.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *CarouselDescription → Items*
 */
export interface TextSliceDefaultItem {
  /**
   * Text Block field in *CarouselDescription → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.items[].text_block
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_block: prismic.RichTextField;
}

/**
 * Default variation for CarouselDescription Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  Simplify<TextSliceDefaultItem>
>;

/**
 * Slice variation for *CarouselDescription*
 */
type TextSliceVariation = TextSliceDefault;

/**
 * CarouselDescription Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

/**
 * Primary content in *WorkCarousel → Default → Primary*
 */
export interface WorkCarouselSliceDefaultPrimary {
  /**
   * Title field in *WorkCarousel → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: work_carousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *WorkCarousel → Items*
 */
export interface WorkCarouselSliceDefaultItem {
  /**
   * CarouselItem field in *WorkCarousel → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: work_carousel.items[].carouselitem
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  carouselitem: prismic.LinkToMediaField;

  /**
   * VideoThumb field in *WorkCarousel → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: work_carousel.items[].thumb
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  thumb: prismic.LinkToMediaField;
}

/**
 * Default variation for WorkCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: WorkCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkCarouselSliceDefaultPrimary>,
  Simplify<WorkCarouselSliceDefaultItem>
>;

/**
 * Slice variation for *WorkCarousel*
 */
type WorkCarouselSliceVariation = WorkCarouselSliceDefault;

/**
 * WorkCarousel Shared Slice
 *
 * - **API ID**: `work_carousel`
 * - **Description**: WorkCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkCarouselSlice = prismic.SharedSlice<
  "work_carousel",
  WorkCarouselSliceVariation
>;

/**
 * Primary content in *WorkGrid → Default → Primary*
 */
export interface WorkGridSliceDefaultPrimary {
  /**
   * Order field in *WorkGrid → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: work_grid.default.primary.order
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;

  /**
   * Negative Order field in *WorkGrid → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: work_grid.default.primary.negative_order
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  negative_order: prismic.NumberField;
}

/**
 * Primary content in *WorkGrid → Items*
 */
export interface WorkGridSliceDefaultItem {
  /**
   * Project Title field in *WorkGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_grid.items[].project_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_title: prismic.KeyTextField;

  /**
   * Description field in *WorkGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_grid.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Work field in *WorkGrid → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: work_grid.items[].work
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  work: prismic.ContentRelationshipField;
}

/**
 * Default variation for WorkGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: WorkGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkGridSliceDefaultPrimary>,
  Simplify<WorkGridSliceDefaultItem>
>;

/**
 * Slice variation for *WorkGrid*
 */
type WorkGridSliceVariation = WorkGridSliceDefault;

/**
 * WorkGrid Shared Slice
 *
 * - **API ID**: `work_grid`
 * - **Description**: WorkGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkGridSlice = prismic.SharedSlice<
  "work_grid",
  WorkGridSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      LandingDocument,
      LandingDocumentData,
      LandingDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSlicesSlice,
      WorkDocument,
      WorkDocumentData,
      WorkDocumentDataSlicesSlice,
      AllDocumentTypes,
      AddressSlice,
      AddressSliceDefaultPrimary,
      AddressSliceDefaultItem,
      AddressSliceVariation,
      AddressSliceDefault,
      ClientLogosSlice,
      ClientLogosSliceDefaultPrimary,
      ClientLogosSliceDefaultItem,
      ClientLogosSliceVariation,
      ClientLogosSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceDefaultItem,
      ContactSliceVariation,
      ContactSliceDefault,
      CookieFooterSlice,
      CookieFooterSliceDefaultPrimary,
      CookieFooterSliceVariation,
      CookieFooterSliceDefault,
      CreditFooterSlice,
      CreditFooterSliceDefaultPrimary,
      CreditFooterSliceVariation,
      CreditFooterSliceDefault,
      HeroTextSlice,
      HeroTextSliceDefaultItem,
      HeroTextSliceVariation,
      HeroTextSliceDefault,
      HeroVideoSlice,
      HeroVideoSliceDefaultPrimary,
      HeroVideoSliceVariation,
      HeroVideoSliceDefault,
      ImageSliceSlice,
      ImageSliceSliceDefaultPrimary,
      ImageSliceSliceVariation,
      ImageSliceSliceDefault,
      LinksSlice,
      LinksSliceDefaultItem,
      LinksSliceVariation,
      LinksSliceDefault,
      MediaArraySlice,
      MediaArraySliceDefaultPrimary,
      MediaArraySliceDefaultItem,
      MediaArraySliceVariation,
      MediaArraySliceDefault,
      PhilosophySlice,
      PhilosophySliceDefaultPrimary,
      PhilosophySliceDefaultItem,
      PhilosophySliceVariation,
      PhilosophySliceDefault,
      ProfileWorkGridSlice,
      ProfileWorkGridSliceDefaultPrimary,
      ProfileWorkGridSliceDefaultItem,
      ProfileWorkGridSliceVariation,
      ProfileWorkGridSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceDefaultItem,
      RichTextSliceVariation,
      RichTextSliceDefault,
      StickyHeaderSlice,
      StickyHeaderSliceDefaultPrimary,
      StickyHeaderSliceVariation,
      StickyHeaderSliceDefault,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceDefaultItem,
      TextSliceVariation,
      TextSliceDefault,
      WorkCarouselSlice,
      WorkCarouselSliceDefaultPrimary,
      WorkCarouselSliceDefaultItem,
      WorkCarouselSliceVariation,
      WorkCarouselSliceDefault,
      WorkGridSlice,
      WorkGridSliceDefaultPrimary,
      WorkGridSliceDefaultItem,
      WorkGridSliceVariation,
      WorkGridSliceDefault,
    };
  }
}
