// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for landing documents */
interface LandingDocumentData {
    /**
     * Title field in *landing*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: landing.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *landing*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: landing.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Keywords field in *landing*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: landing.keywords
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    keywords: prismicT.KeyTextField;
    /**
     * Slice Zone field in *landing*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: landing.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<LandingDocumentDataSlicesSlice>;
}
/**
 * Slice for *landing → Slice Zone*
 *
 */
type LandingDocumentDataSlicesSlice = ClientLogosSlice | StickyHeaderSlice | WorkGridSlice | ContactSlice | HeroVideoSlice | CreditFooterSlice | CookieFooterSlice | PhilosophySlice;
/**
 * landing document from Prismic
 *
 * - **API ID**: `landing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<LandingDocumentData>, "landing", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Descript field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Keywords field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.keywords
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    keywords: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = WorkGridSlice | ImageSliceSlice | RichTextSlice | ContactSlice | HeroTextSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Work documents */
interface WorkDocumentData {
    /**
     * Title field in *Work*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Work*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Keywords field in *Work*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work.keywords
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    keywords: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Work*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: work.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<WorkDocumentDataSlicesSlice>;
}
/**
 * Slice for *Work → Slice Zone*
 *
 */
type WorkDocumentDataSlicesSlice = WorkCarouselSlice | TextSlice;
/**
 * Work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<WorkDocumentData>, "work", Lang>;
export type AllDocumentTypes = LandingDocument | PageDocument | WorkDocument;
/**
 * Primary content in Article → Primary
 *
 */
interface RichTextSliceDefaultPrimary {
    /**
     * Title field in *Article → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: rich_text.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Item in Article → Items
 *
 */
export interface RichTextSliceDefaultItem {
    /**
     * Content field in *Article → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: rich_text.items[].content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Default variation for Article Slice
 *
 * - **API ID**: `default`
 * - **Description**: `RichText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RichTextSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<RichTextSliceDefaultPrimary>, Simplify<RichTextSliceDefaultItem>>;
/**
 * Slice variation for *Article*
 *
 */
type RichTextSliceVariation = RichTextSliceDefault;
/**
 * Article Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: `RichText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RichTextSlice = prismicT.SharedSlice<"rich_text", RichTextSliceVariation>;
/**
 * Primary content in CarouselDescription → Primary
 *
 */
interface TextSliceDefaultPrimary {
    /**
     * Title field in *CarouselDescription → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: text.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *CarouselDescription → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: text.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in CarouselDescription → Items
 *
 */
export interface TextSliceDefaultItem {
    /**
     * Text Block field in *CarouselDescription → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text.items[].text_block
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text_block: prismicT.RichTextField;
}
/**
 * Default variation for CarouselDescription Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TextSliceDefaultPrimary>, Simplify<TextSliceDefaultItem>>;
/**
 * Slice variation for *CarouselDescription*
 *
 */
type TextSliceVariation = TextSliceDefault;
/**
 * CarouselDescription Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSlice = prismicT.SharedSlice<"text", TextSliceVariation>;
/**
 * Primary content in ClientLogos → Primary
 *
 */
interface ClientLogosSliceDefaultPrimary {
    /**
     * Title field in *ClientLogos → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: client_logos.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Order field in *ClientLogos → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: client_logos.primary.order
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    order: prismicT.NumberField;
    /**
     * Negative Order field in *ClientLogos → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: client_logos.primary.negative_order
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    negative_order: prismicT.NumberField;
    /**
     * SubOrder field in *ClientLogos → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: client_logos.primary.suborder
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    suborder: prismicT.NumberField;
}
/**
 * Item in ClientLogos → Items
 *
 */
export interface ClientLogosSliceDefaultItem {
    /**
     * Logo field in *ClientLogos → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: client_logos.items[].logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * link field in *ClientLogos → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: client_logos.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Default variation for ClientLogos Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ClientLogos`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ClientLogosSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ClientLogosSliceDefaultPrimary>, Simplify<ClientLogosSliceDefaultItem>>;
/**
 * Slice variation for *ClientLogos*
 *
 */
type ClientLogosSliceVariation = ClientLogosSliceDefault;
/**
 * ClientLogos Shared Slice
 *
 * - **API ID**: `client_logos`
 * - **Description**: `ClientLogos`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ClientLogosSlice = prismicT.SharedSlice<"client_logos", ClientLogosSliceVariation>;
/**
 * Primary content in Contact → Primary
 *
 */
interface ContactSliceDefaultPrimary {
    /**
     * Order field in *Contact → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: contact.primary.order
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    order: prismicT.NumberField;
    /**
     * Negative Order field in *Contact → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: contact.primary.negative_order
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    negative_order: prismicT.NumberField;
}
/**
 * Item in Contact → Items
 *
 */
export interface ContactSliceDefaultItem {
    /**
     * Title field in *Contact → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: contact.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Address field in *Contact → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Address...
     * - **API ID Path**: contact.items[].address
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    address: prismicT.RichTextField;
    /**
     * Maps Link field in *Contact → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: contact.items[].maps_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    maps_link: prismicT.LinkField;
    /**
     * Phone field in *Contact → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: tel:1234567890
     * - **API ID Path**: contact.items[].phone
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    phone: prismicT.LinkField;
    /**
     * Email field in *Contact → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: mailto:abc@def.gh
     * - **API ID Path**: contact.items[].email
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    email: prismicT.LinkField;
    /**
     * TimeZone field in *Contact → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: America/New_York
     * - **API ID Path**: contact.items[].timezone
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    timezone: prismicT.KeyTextField;
}
/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Contact`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContactSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ContactSliceDefaultPrimary>, Simplify<ContactSliceDefaultItem>>;
/**
 * Slice variation for *Contact*
 *
 */
type ContactSliceVariation = ContactSliceDefault;
/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: `Contact`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContactSlice = prismicT.SharedSlice<"contact", ContactSliceVariation>;
/**
 * Primary content in CookieFooter → Primary
 *
 */
interface CookieFooterSliceDefaultPrimary {
    /**
     * Content field in *CookieFooter → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cookie_footer.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * ImprintLink field in *CookieFooter → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: cookie_footer.primary.imprintlink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    imprintlink: prismicT.RelationField;
    /**
     * Order field in *CookieFooter → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: cookie_footer.primary.order
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    order: prismicT.NumberField;
    /**
     * Negative Order field in *CookieFooter → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: cookie_footer.primary.negative_order
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    negative_order: prismicT.NumberField;
}
/**
 * Default variation for CookieFooter Slice
 *
 * - **API ID**: `default`
 * - **Description**: `CookieFooter`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CookieFooterSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<CookieFooterSliceDefaultPrimary>, never>;
/**
 * Slice variation for *CookieFooter*
 *
 */
type CookieFooterSliceVariation = CookieFooterSliceDefault;
/**
 * CookieFooter Shared Slice
 *
 * - **API ID**: `cookie_footer`
 * - **Description**: `CookieFooter`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CookieFooterSlice = prismicT.SharedSlice<"cookie_footer", CookieFooterSliceVariation>;
/**
 * Primary content in CreditFooter → Primary
 *
 */
interface CreditFooterSliceDefaultPrimary {
    /**
     * Line One field in *CreditFooter → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: credit_footer.primary.line_one
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    line_one: prismicT.KeyTextField;
    /**
     * Line Two field in *CreditFooter → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: credit_footer.primary.line_two
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    line_two: prismicT.KeyTextField;
    /**
     * Order field in *CreditFooter → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: credit_footer.primary.order
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    order: prismicT.NumberField;
    /**
     * Negative Order field in *CreditFooter → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: credit_footer.primary.negative_order
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    negative_order: prismicT.NumberField;
    /**
     * Logo field in *CreditFooter → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: credit_footer.primary.logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
}
/**
 * Default variation for CreditFooter Slice
 *
 * - **API ID**: `default`
 * - **Description**: `CreditFooter`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CreditFooterSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<CreditFooterSliceDefaultPrimary>, never>;
/**
 * Slice variation for *CreditFooter*
 *
 */
type CreditFooterSliceVariation = CreditFooterSliceDefault;
/**
 * CreditFooter Shared Slice
 *
 * - **API ID**: `credit_footer`
 * - **Description**: `CreditFooter`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CreditFooterSlice = prismicT.SharedSlice<"credit_footer", CreditFooterSliceVariation>;
/**
 * Item in HeroText → Items
 *
 */
export interface HeroTextSliceDefaultItem {
    /**
     * Hero Text field in *HeroText → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_text.items[].hero_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    hero_text: prismicT.KeyTextField;
}
/**
 * Default variation for HeroText Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeroText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroTextSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<HeroTextSliceDefaultItem>>;
/**
 * Slice variation for *HeroText*
 *
 */
type HeroTextSliceVariation = HeroTextSliceDefault;
/**
 * HeroText Shared Slice
 *
 * - **API ID**: `hero_text`
 * - **Description**: `HeroText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroTextSlice = prismicT.SharedSlice<"hero_text", HeroTextSliceVariation>;
/**
 * Primary content in HeroVideo → Primary
 *
 */
interface HeroVideoSliceDefaultPrimary {
    /**
     * VideoLink field in *HeroVideo → Primary*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_video.primary.videolink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    videolink: prismicT.LinkToMediaField;
}
/**
 * Default variation for HeroVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeroVideo`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroVideoSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroVideoSliceDefaultPrimary>, never>;
/**
 * Slice variation for *HeroVideo*
 *
 */
type HeroVideoSliceVariation = HeroVideoSliceDefault;
/**
 * HeroVideo Shared Slice
 *
 * - **API ID**: `hero_video`
 * - **Description**: `HeroVideo`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroVideoSlice = prismicT.SharedSlice<"hero_video", HeroVideoSliceVariation>;
/**
 * Primary content in ImageSlice → Primary
 *
 */
interface ImageSliceSliceDefaultPrimary {
    /**
     * Title field in *ImageSlice → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: image_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Image field in *ImageSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image_slice.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for ImageSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ImageSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImageSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ImageSlice*
 *
 */
type ImageSliceSliceVariation = ImageSliceSliceDefault;
/**
 * ImageSlice Shared Slice
 *
 * - **API ID**: `image_slice`
 * - **Description**: `ImageSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSliceSlice = prismicT.SharedSlice<"image_slice", ImageSliceSliceVariation>;
/**
 * Primary content in MediaArray → Primary
 *
 */
interface MediaArraySliceDefaultPrimary {
    /**
     * Title field in *MediaArray → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: media_array.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Item in MediaArray → Items
 *
 */
export interface MediaArraySliceDefaultItem {
    /**
     * media field in *MediaArray → Items*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: media_array.items[].media
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    media: prismicT.LinkToMediaField;
}
/**
 * Default variation for MediaArray Slice
 *
 * - **API ID**: `default`
 * - **Description**: `MediaArray`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MediaArraySliceDefault = prismicT.SharedSliceVariation<"default", Simplify<MediaArraySliceDefaultPrimary>, Simplify<MediaArraySliceDefaultItem>>;
/**
 * Slice variation for *MediaArray*
 *
 */
type MediaArraySliceVariation = MediaArraySliceDefault;
/**
 * MediaArray Shared Slice
 *
 * - **API ID**: `media_array`
 * - **Description**: `MediaArray`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MediaArraySlice = prismicT.SharedSlice<"media_array", MediaArraySliceVariation>;
/**
 * Primary content in Philosophy → Primary
 *
 */
interface PhilosophySliceDefaultPrimary {
    /**
     * Title field in *Philosophy → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: philosophy.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * SubOrder field in *Philosophy → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: philosophy.primary.suborder
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    suborder: prismicT.NumberField;
    /**
     * Order field in *Philosophy → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: philosophy.primary.order
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    order: prismicT.NumberField;
}
/**
 * Item in Philosophy → Items
 *
 */
export interface PhilosophySliceDefaultItem {
    /**
     * Type field in *Philosophy → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: philosophy.items[].type
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    type: prismicT.SelectField<"Description with image" | "List">;
    /**
     * Category field in *Philosophy → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: philosophy.items[].category
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    category: prismicT.TitleField;
    /**
     * Description field in *Philosophy → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: philosophy.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Image field in *Philosophy → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: philosophy.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * List Heading field in *Philosophy → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: philosophy.items[].list_heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    list_heading: prismicT.TitleField;
    /**
     * List field in *Philosophy → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: philosophy.items[].list
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    list: prismicT.RichTextField;
    /**
     * text field in *Philosophy → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: philosophy.items[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
}
/**
 * Default variation for Philosophy Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Philosophy`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PhilosophySliceDefault = prismicT.SharedSliceVariation<"default", Simplify<PhilosophySliceDefaultPrimary>, Simplify<PhilosophySliceDefaultItem>>;
/**
 * Slice variation for *Philosophy*
 *
 */
type PhilosophySliceVariation = PhilosophySliceDefault;
/**
 * Philosophy Shared Slice
 *
 * - **API ID**: `philosophy`
 * - **Description**: `Philosophy`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PhilosophySlice = prismicT.SharedSlice<"philosophy", PhilosophySliceVariation>;
/**
 * Primary content in StickyHeader → Primary
 *
 */
interface StickyHeaderSliceDefaultPrimary {
    /**
     * Title field in *StickyHeader → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: sticky_header.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Order field in *StickyHeader → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: sticky_header.primary.order
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    order: prismicT.NumberField;
    /**
     * Negative Order field in *StickyHeader → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: sticky_header.primary.negative_order
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    negative_order: prismicT.NumberField;
}
/**
 * Default variation for StickyHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: `StickyHeader`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type StickyHeaderSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<StickyHeaderSliceDefaultPrimary>, never>;
/**
 * Slice variation for *StickyHeader*
 *
 */
type StickyHeaderSliceVariation = StickyHeaderSliceDefault;
/**
 * StickyHeader Shared Slice
 *
 * - **API ID**: `sticky_header`
 * - **Description**: `StickyHeader`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type StickyHeaderSlice = prismicT.SharedSlice<"sticky_header", StickyHeaderSliceVariation>;
/**
 * Primary content in Structure → Primary
 *
 */
interface StructureSliceDefaultPrimary {
    /**
     * Title field in *Structure → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: structure.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * SubOrder field in *Structure → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: structure.primary.suborder
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    suborder: prismicT.NumberField;
    /**
     * Order field in *Structure → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: structure.primary.order
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    order: prismicT.NumberField;
}
/**
 * Item in Structure → Items
 *
 */
export interface StructureSliceDefaultItem {
    /**
     * Location field in *Structure → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: structure.items[].location
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    location: prismicT.TitleField;
    /**
     * Category Title field in *Structure → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: structure.items[].category_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    category_title: prismicT.TitleField;
    /**
     * List field in *Structure → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: structure.items[].list
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    list: prismicT.RichTextField;
}
/**
 * Default variation for Structure Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Structure`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type StructureSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<StructureSliceDefaultPrimary>, Simplify<StructureSliceDefaultItem>>;
/**
 * Slice variation for *Structure*
 *
 */
type StructureSliceVariation = StructureSliceDefault;
/**
 * Structure Shared Slice
 *
 * - **API ID**: `structure`
 * - **Description**: `Structure`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type StructureSlice = prismicT.SharedSlice<"structure", StructureSliceVariation>;
/**
 * Primary content in WorkCarousel → Primary
 *
 */
interface WorkCarouselSliceDefaultPrimary {
    /**
     * Title field in *WorkCarousel → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: work_carousel.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Item in WorkCarousel → Items
 *
 */
export interface WorkCarouselSliceDefaultItem {
    /**
     * CarouselItem field in *WorkCarousel → Items*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: work_carousel.items[].carouselitem
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    carouselitem: prismicT.LinkToMediaField;
    /**
     * VideoThumb field in *WorkCarousel → Items*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: work_carousel.items[].thumb
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    thumb: prismicT.LinkToMediaField;
}
/**
 * Default variation for WorkCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: `WorkCarousel`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type WorkCarouselSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<WorkCarouselSliceDefaultPrimary>, Simplify<WorkCarouselSliceDefaultItem>>;
/**
 * Slice variation for *WorkCarousel*
 *
 */
type WorkCarouselSliceVariation = WorkCarouselSliceDefault;
/**
 * WorkCarousel Shared Slice
 *
 * - **API ID**: `work_carousel`
 * - **Description**: `WorkCarousel`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type WorkCarouselSlice = prismicT.SharedSlice<"work_carousel", WorkCarouselSliceVariation>;
/**
 * Primary content in WorkGrid → Primary
 *
 */
interface WorkGridSliceDefaultPrimary {
    /**
     * Order field in *WorkGrid → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: work_grid.primary.order
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    order: prismicT.NumberField;
    /**
     * Negative Order field in *WorkGrid → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: work_grid.primary.negative_order
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    negative_order: prismicT.NumberField;
}
/**
 * Item in WorkGrid → Items
 *
 */
export interface WorkGridSliceDefaultItem {
    /**
     * Project Link field in *WorkGrid → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: work_grid.items[].worklink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    worklink: prismicT.RelationField;
    /**
     * Project Title field in *WorkGrid → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work_grid.items[].project_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    project_title: prismicT.KeyTextField;
    /**
     * MediaForGrid field in *WorkGrid → Items*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: work_grid.items[].mediaforgrid
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    mediaforgrid: prismicT.LinkToMediaField;
    /**
     * Description field in *WorkGrid → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work_grid.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Year field in *WorkGrid → Items*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: work_grid.items[].year
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    year: prismicT.NumberField;
    /**
     * Work field in *WorkGrid → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: work_grid.items[].work
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    work: prismicT.RelationField;
}
/**
 * Default variation for WorkGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: `WorkGrid`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type WorkGridSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<WorkGridSliceDefaultPrimary>, Simplify<WorkGridSliceDefaultItem>>;
/**
 * Slice variation for *WorkGrid*
 *
 */
type WorkGridSliceVariation = WorkGridSliceDefault;
/**
 * WorkGrid Shared Slice
 *
 * - **API ID**: `work_grid`
 * - **Description**: `WorkGrid`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type WorkGridSlice = prismicT.SharedSlice<"work_grid", WorkGridSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { LandingDocumentData, LandingDocumentDataSlicesSlice, LandingDocument, PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, WorkDocumentData, WorkDocumentDataSlicesSlice, WorkDocument, AllDocumentTypes, RichTextSliceDefaultPrimary, RichTextSliceDefaultItem, RichTextSliceDefault, RichTextSliceVariation, RichTextSlice, TextSliceDefaultPrimary, TextSliceDefaultItem, TextSliceDefault, TextSliceVariation, TextSlice, ClientLogosSliceDefaultPrimary, ClientLogosSliceDefaultItem, ClientLogosSliceDefault, ClientLogosSliceVariation, ClientLogosSlice, ContactSliceDefaultPrimary, ContactSliceDefaultItem, ContactSliceDefault, ContactSliceVariation, ContactSlice, CookieFooterSliceDefaultPrimary, CookieFooterSliceDefault, CookieFooterSliceVariation, CookieFooterSlice, CreditFooterSliceDefaultPrimary, CreditFooterSliceDefault, CreditFooterSliceVariation, CreditFooterSlice, HeroTextSliceDefaultItem, HeroTextSliceDefault, HeroTextSliceVariation, HeroTextSlice, HeroVideoSliceDefaultPrimary, HeroVideoSliceDefault, HeroVideoSliceVariation, HeroVideoSlice, ImageSliceSliceDefaultPrimary, ImageSliceSliceDefault, ImageSliceSliceVariation, ImageSliceSlice, MediaArraySliceDefaultPrimary, MediaArraySliceDefaultItem, MediaArraySliceDefault, MediaArraySliceVariation, MediaArraySlice, PhilosophySliceDefaultPrimary, PhilosophySliceDefaultItem, PhilosophySliceDefault, PhilosophySliceVariation, PhilosophySlice, StickyHeaderSliceDefaultPrimary, StickyHeaderSliceDefault, StickyHeaderSliceVariation, StickyHeaderSlice, StructureSliceDefaultPrimary, StructureSliceDefaultItem, StructureSliceDefault, StructureSliceVariation, StructureSlice, WorkCarouselSliceDefaultPrimary, WorkCarouselSliceDefaultItem, WorkCarouselSliceDefault, WorkCarouselSliceVariation, WorkCarouselSlice, WorkGridSliceDefaultPrimary, WorkGridSliceDefaultItem, WorkGridSliceDefault, WorkGridSliceVariation, WorkGridSlice };
    }
}
