// Code generated by Slice Machine. DO NOT EDIT.

import Address from './Address';
import Article from './Article';
import CarouselDescription from './CarouselDescription';
import ClientLogos from './ClientLogos';
import Contact from './Contact';
import HeroText from './HeroText';
import HeroVideo from './HeroVideo';
import ImageSlice from './ImageSlice';
import Links from './Links';
import MediaArray from './MediaArray';
import Philosophy from './Philosophy';
import ProfileWorkGrid from './ProfileWorkGrid';
import StickyHeader from './StickyHeader';
import WorkCarousel from './WorkCarousel';
import WorkGrid from './WorkGrid';

export {
	Address,
	Article,
	CarouselDescription,
	ClientLogos,
	Contact,

	HeroText,
	HeroVideo,
	ImageSlice,
	Links,
	MediaArray,
	Philosophy,
	ProfileWorkGrid,
	StickyHeader,
	WorkCarousel,
	WorkGrid,
};

export const components = {
	address: Address,
	rich_text: Article,
	text: CarouselDescription,
	client_logos: ClientLogos,
	contact: Contact,

	hero_text: HeroText,
	hero_video: HeroVideo,
	image_slice: ImageSlice,
	links: Links,
	media_array: MediaArray,
	philosophy: Philosophy,
	profile_work_grid: ProfileWorkGrid,
	sticky_header: StickyHeader,
	work_carousel: WorkCarousel,
	work_grid: WorkGrid,
};
