// Code generated by Slice Machine. DO NOT EDIT.

import Article from './Article';
import CarouselDescription from './CarouselDescription';
import ClientLogos from './ClientLogos';
import Contact from './Contact';
import CookieFooter from './CookieFooter';
import CreditFooter from './CreditFooter';
import HeroText from './HeroText';
import HeroVideo from './HeroVideo';
import ImageSlice from './ImageSlice';
import MediaArray from './MediaArray';
import Philosophy from './Philosophy';
import StickyHeader from './StickyHeader';
import Structure from './Structure';
import WorkCarousel from './WorkCarousel';
import WorkGrid from './WorkGrid';

export {
	Article,
	CarouselDescription,
	ClientLogos,
	Contact,
	CookieFooter,
	CreditFooter,
	HeroText,
	HeroVideo,
	ImageSlice,
	MediaArray,
	Philosophy,
	StickyHeader,
	Structure,
	WorkCarousel,
	WorkGrid,
};

export const components = {
	rich_text: Article,
	text: CarouselDescription,
	client_logos: ClientLogos,
	contact: Contact,
	cookie_footer: CookieFooter,
	credit_footer: CreditFooter,
	hero_text: HeroText,
	hero_video: HeroVideo,
	image_slice: ImageSlice,
	media_array: MediaArray,
	philosophy: Philosophy,
	sticky_header: StickyHeader,
	structure: Structure,
	work_carousel: WorkCarousel,
	work_grid: WorkGrid,
};
